---
title: "Assignment 2"
author: "Galen M"
date: "January 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 2, EE283

## Attempt with base R:

Aped from [stackoverflow](https://stackoverflow.com/questions/10077415/replacing-nas-in-r-with-nearest-value):
```{R}
data <- read.table("data.txt", header = TRUE)
data$index <- 1:14
data$tfindex <- ifelse(data$value == 1, data$index, NA)

f1 <- function(dat) {
  N <- length(dat)
  na.pos <- which(is.na(dat))
  if (length(na.pos) %in% c(0, N)) {
    return(dat)
  }
  non.na.pos <- which(!is.na(dat))
  intervals  <- findInterval(na.pos, non.na.pos,
                             all.inside = TRUE)
  left.pos   <- non.na.pos[pmax(1, intervals)]
  right.pos  <- non.na.pos[pmin(N, intervals+1)]
  left.dist  <- na.pos - left.pos
  right.dist <- right.pos - na.pos
  
  dat[na.pos] <- ifelse(left.dist <= right.dist,
                        dat[left.pos], dat[right.pos])
  return(dat)
}

apply(data, 2, f1)
```

I think there's probably a way to to do this using the hist() function as well, I just haven't quite figured it out yet.
```{r}
histbreaks <- c(0, which(!is.na(data$tfindex)), 15)
histo <- hist(data$index, breaks = histbreaks, plot = FALSE)
histo$counts
#etc etc
```

## Using dplyr:
